export const authConstants = {
  SIGNIN_REQUEST:'SIGNIN_REQUEST',
  SIGNIN_SUCCESS:'SIGNIN_SUCCESS',
  SIGNIN_FAILURE:'SIGNIN_FAILURE',
  SIGNOUT_REQUEST:'SIGNOUT_REQUEST',
  SIGNOUT_SUCCESS:'SIGNOUT_SUCCESS',
  SIGNOUT_FAILURE:'SIGNOUT_FAILURE',
  
}
export const userConstants = {
  SIGNUP_REQUEST:'SIGNUP_REQUEST',
  SIGNUP_SUCCESS:'SIGNUP_SUCCESS',
  SIGNUP_FAILURE:'SIGNUP_FAILURE',
}
export const postsConstants = {
  GET_ALL_REQUEST : 'GET_ALL_REQUEST',
  GET_ALL_SUCCESS : 'GET_ALL_SUCCESS',
  GET_ALL_FAILURE : 'GET_ALL_FAILURE',
  GET_ALL_USERS_SUCCESS:'GET_ALL_USERS_SUCCESS',
  GET_ALL_USERS_FAILURE:'GET_ALL_USERS_FAILURE'
}